### ISSUE TITLE
the regex for PING needs some tuning?

### ISSUE THREAD

**Issue by ilias-sp** [RickyB98/TwitchBot#2]
i am getting this while running the script:

PHP Notice:  Undefined offset: 1 in /php_basedir/VARIOUS_STUFF/TWITCH/CHAT_BOT/TEMP/TwitchBot/twitchbot.php on line 30

i believe this line needs fix:

if (preg_match("/PING :.*/i", $read, $match)) { fwrite($fp, "PONG :$match[1]\r\n"); }

to (parentheseis between .*):  

if (preg_match("/PING :(.*)/i", $read, $match)) { fwrite($fp, "PONG :$match[1]\r\n"); }

**Comment by RickyB98** [comment]
I suppose your fix is correct. I do not maintain that script anymore, could you make a pull request? I would be happy to merge it! :)

**Comment by ilias-sp** [comment]
done, i hope i did the git stuff right (first time xd) , its here: #3
